robot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers ---------------------------------------
  joint_1_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_1
    pid: {p: 100, i: 0.01, d: 10, i_clamp_min: -40.0, i_clamp_max: 40.0, antiwindup: true}
  joint_2_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_2
    pid: {p: 100, i: 0.01, d: 10, i_clamp_min: -40.0, i_clamp_max: 40.0, antiwindup: true}
  joint_3_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_3
    pid: {p: 100, i: 0.01, d: 10, i_clamp_min: -40.0, i_clamp_max: 40.0, antiwindup: true}
  joint_4_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_4
    pid: {p: 500, i: 0.1, d: 1, i_clamp_min: -40.0, i_clamp_max: 40.0, antiwindup: true}
  joint_5_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_5
    pid: {p: 300, i: 0.1, d: 2, i_clamp_min: -40.0, i_clamp_max: 40.0, antiwindup: true}
  joint_6_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_6
    pid: {p: 700, i: 0.1, d: 1, i_clamp_min: -40.0, i_clamp_max: 40.0, antiwindup: true}
